### ISSUE TITLE
Adding a License

### ISSUE THREAD

**Issue by cethemaco** [rghv96/type2learn#2]
I noticed that the repo doesn't have a license that people can refer to.
I think that a permissive license like the MIT License would be appropiate, so that people (right now, only me) could add features to their without being entirely dependent on you, @rghv96.

**Comment by rghv96** [comment]
The license is present in the readme.

**Comment by cethemaco** [comment]
Yes, I noticed that, which I why I closed that Issue 😅 
I was just confused since normally there is an extra file that has the license explicitly
